printk: add stub for prepend_timestamp()
Add a stub for prepend_timestamp() when CONFIG_PRINTK is not
enabled.  Fixes this build error:

kernel/printk.c:1770:3: error: implicit declaration of function 'prepend_timestamp'

Change-Id: I4ac7ee2b6230fc0b211ae439ea6774716e9454a9
Cc: Kay Sievers <kay@vrfy.org>
Signed-off-by: Randy Dunlap <rdunlap@xenotime.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

(cherry picked from commit b360d4ee5abe29bc8c653d7ec5d4d6f326fa2944)

(cherry picked from commit 42fc37fde3ecc5e05cdae698b02b16ff6a4600ed)

(cherry picked from commit a3a8903c401e4176801b83c52064e2f5d676de27)

(cherry picked from commit 1149c0aec769b94bf1c7078035840383da0f5c46)